### PR TITLE
fix 'Key cannot contain a space' error

### PR DESCRIPTION
**Pull request by sg4tech**

### CODE REVIEW

**Comment by Tinitto** [comment]
@glendemon , is it possible to create an issue to describe the error you are trying to solve with this pull request.
Please also include the versions of docker and docker-compose.

**Comment by JustStas** [comment]
@Tinitto I faced this issue when running docker-compose on my mac. The proposed fix seems to have solved the issue. I would recommend to approve it.

**Comment by Tinitto** [comment]
@JustStas I actually expect the issue to be authentic but for a certain version of docker or docker compose because I have actually been able to run it on a Mac with the current settings.

If I just accept the PR without being able to verify that it works, and it breaks the setups of others for whom the current setting was working, it will be trouble for me.

Just get me the version numbers so that I can verify...and maybe even document that this or that setting works up to this or that version of this or that library or system or whatever.

**Comment by komkomissarov** [comment]
I have the same error with this docker-compose.file
```
version: "3.8"

# All available services
services:

  # Misc Storage
  postgres:
    container_name: "data_engine_postgres"
    restart: "always"
    image: postgres:alpine
    env_file:
      - ./postgres.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./postgres_init_scripts/:/docker-entrypoint-initdb.d/
      - /dev/urandom:/dev/random:ro
      # Без понятия нахрена оно ему надо, но в офицаильной доке это было

  metabase:
    container_name: "data_engine_metabase"
    restart: "always"
    image: metabase/metabase:latest
    env_file:
      - ./metabase_database.env
    ports:
      - 3000:3000

# Volumes to persist data
volumes:
  postgres_volume:
```

env files identical to repo. 

docker-compose up-d show 
key cannot contain a space

this PR really fix the error for me after 30 minutes of brain fuck with docker-compose file)

Docker version 23.0.2, build 569dd73
Docker Compose version v2.6.0
Ubuntu 20.04

**Comment by Tinitto** [comment]
@komkomissarov thanks for the details...Sorry for the headache. Let me verify and merge if all is good.

**Review by Tinitto — APPROVED** [review]

**Pull request merged**
